controller_names:
  - joint_trajectory_controller

joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - arm_shoulder
    - arm_upper_arm
    - arm_forearm
    - arm_wrist_1
    - arm_wrist_2
    - arm_wrist_3